version: '3.2'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
        - ${PORT}:5432
    volumes: 
        - pgdata:/var/lib/postgresql/data
  
  django:
    build: .
    volumes:
      - "/io/:/code/"
    command: ["/wait.sh", "python3", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "80:8000"
    depends_on: ["postgres"]
      
volumes:
  pgdata:
